#!/usr/bin/env bash
# Tracedown installer — "k8s" mode. Sourced by install.sh, which provides the
# shared helpers (prompt, say, confirm_dir, prompt_email, ...) and the TD_*
# environment contract. Not runnable on its own.

install_k8s() {
  say "Kubernetes: the monolith on a cluster — plain manifests, no Helm required."
  note "(The per-service stack on Kubernetes is a chart-sized project; the"
  note " monolith is the supported cluster install today.)"

  prompt TD_DIR       "Directory for the generated manifests" "$HOME/tracedown-k8s"
  prompt TD_VERSION   "Backend version (or 'latest')"         "latest"
  prompt TD_NAMESPACE "Namespace"                             "tracedown"
  prompt TD_INGRESS_HOST "Ingress host (empty or 'none': no Ingress — use port-forward)" "none"
  [ "$TD_INGRESS_HOST" = "none" ] && TD_INGRESS_HOST=""
  prompt_admin
  prompt_email

  [ "$TD_VERSION" = "latest" ] && TD_VERSION="$(latest_backend_version)"
  [ -n "$TD_VERSION" ] || die "Could not resolve the latest release."
  confirm_dir "$TD_DIR"; cd "$TD_DIR"

  local deploy_env="" ws_url="" app_url=""
  [ "$TD_EMAIL_MODE" = "smtp" ] && deploy_env="production"
  [ -n "$TD_INGRESS_HOST" ] && ws_url="/ws"
  # Invite and password-reset mails are built from APP_URL. With an Ingress it
  # is that host; without one the only way in is the port-forward this mode
  # prints at the end, so say so rather than leave it empty — the platform
  # treats a defined-but-empty value as an override and would emit bare paths.
  if [ -n "$TD_INGRESS_HOST" ]; then app_url="http://${TD_INGRESS_HOST}"; else app_url="http://127.0.0.1:20714"; fi
  local jar_url="https://github.com/${BACKEND_REPO}/releases/download/v${TD_VERSION}/tracedown-monolith-${TD_VERSION}-all.jar"

  say "Writing tracedown.yaml (version ${TD_VERSION}) ..."
  cat > tracedown.yaml <<YAML
# Tracedown monolith on Kubernetes — generated by install.sh.
# Secrets are generated once, below; PLATFORM_AES_KEY is permanent (it
# encrypts stored secrets and cannot be rotated) — back this file up, or move
# the Secret into your secret manager.
apiVersion: v1
kind: Namespace
metadata:
  name: ${TD_NAMESPACE}
---
apiVersion: v1
kind: Secret
metadata:
  name: tracedown-secrets
  namespace: ${TD_NAMESPACE}
stringData:
  PLATFORM_AES_KEY: "$(hex32)"
  JWT_SECRET: "$(b64secret)"
  DB_PASSWORD: "$(openssl rand -hex 16)"
  DEMO_USER_EMAIL: "${TD_DEMO_EMAIL}"
  DEMO_USER_PASSWORD: "${TD_DEMO_PASSWORD}"
  SMTP_PASSWORD: "${TD_SMTP_PASSWORD:-}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: tracedown-pgdata, namespace: ${TD_NAMESPACE} }
spec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 10Gi } } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: tracedown-redis, namespace: ${TD_NAMESPACE} }
spec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 2Gi } } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: tracedown-bodies, namespace: ${TD_NAMESPACE} }
spec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 5Gi } } }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: ${TD_NAMESPACE}
spec:
  serviceName: postgres
  replicas: 1
  selector: { matchLabels: { app: postgres } }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - { name: POSTGRES_DB, value: tracedown }
            - { name: POSTGRES_USER, value: tracedown }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: tracedown-secrets, key: DB_PASSWORD } }
          ports: [{ containerPort: 5432 }]
          # Postgres serves no /health of its own; pg_isready is the readiness
          # answer and an open socket the liveness one. Without these the
          # database counts as Ready the instant the container starts, and the
          # monolith's first connection attempt races initdb.
          livenessProbe:
            tcpSocket: { port: 5432 }
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec: { command: ["pg_isready", "-U", "tracedown", "-d", "tracedown"] }
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts: [{ name: pgdata, mountPath: /var/lib/postgresql/data }]
      volumes:
        - name: pgdata
          persistentVolumeClaim: { claimName: tracedown-pgdata }
---
apiVersion: v1
kind: Service
metadata: { name: postgres, namespace: ${TD_NAMESPACE} }
spec:
  selector: { app: postgres }
  ports: [{ port: 5432 }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ${TD_NAMESPACE}
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector: { matchLabels: { app: redis } }
  template:
    metadata: { labels: { app: redis } }
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          args: ["redis-server", "--appendonly", "yes"]
          ports: [{ containerPort: 6379 }]
          livenessProbe:
            tcpSocket: { port: 6379 }
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec: { command: ["redis-cli", "ping"] }
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts: [{ name: data, mountPath: /data }]
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: tracedown-redis }
---
apiVersion: v1
kind: Service
metadata: { name: redis, namespace: ${TD_NAMESPACE} }
spec:
  selector: { app: redis }
  ports: [{ port: 6379 }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracedown
  namespace: ${TD_NAMESPACE}
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector: { matchLabels: { app: tracedown } }
  template:
    metadata: { labels: { app: tracedown } }
    spec:
      initContainers:
        # The release jar is fetched at pod start — upgrading is editing the
        # URL below (or regenerating with a newer version) and restarting.
        - name: fetch
          image: curlimages/curl:latest
          args: ["-fsSL", "-o", "/app/monolith.jar", "${jar_url}"]
          volumeMounts: [{ name: app, mountPath: /app }]
      containers:
        - name: monolith
          image: eclipse-temurin:17-jre
          command: ["java", "-jar", "/app/monolith.jar"]
          env:
            - { name: DATABASE_URL, value: "jdbc:postgresql://postgres:5432/tracedown" }
            - { name: DATABASE_USER, value: tracedown }
            - name: DATABASE_PASSWORD
              valueFrom: { secretKeyRef: { name: tracedown-secrets, key: DB_PASSWORD } }
            - { name: REDIS_A_URL, value: "redis://redis:6379" }
            - name: PLATFORM_AES_KEY
              valueFrom: { secretKeyRef: { name: tracedown-secrets, key: PLATFORM_AES_KEY } }
            - name: JWT_SECRET
              valueFrom: { secretKeyRef: { name: tracedown-secrets, key: JWT_SECRET } }
            # First-run bootstrap: creates the organization and its owner from
            # the two values below. Nothing else in the platform can create the
            # first user, and a Deployment env map is the only thing the
            # process reads — there is no .env here. Set it to "false" and
            # re-apply once you have signed in.
            - { name: SINGLE_ORG_MODE, value: "true" }
            - name: DEMO_USER_EMAIL
              valueFrom: { secretKeyRef: { name: tracedown-secrets, key: DEMO_USER_EMAIL } }
            - name: DEMO_USER_PASSWORD
              valueFrom: { secretKeyRef: { name: tracedown-secrets, key: DEMO_USER_PASSWORD } }
            - { name: STORAGE_FILESYSTEM_ROOT, value: /data/bodies }
            - { name: DEPLOYMENT_ENV, value: "${deploy_env}" }
            - { name: WS_URL, value: "${ws_url}" }
            - { name: APP_URL, value: "${app_url}" }
            - { name: EMAIL_PROVIDER, value: "${TD_EMAIL_MODE/none/console}" }
            - { name: EMAIL_FROM_ADDRESS, value: "${TD_EMAIL_FROM:-noreply@tracedown.dev}" }
            - { name: SMTP_HOST, value: "${TD_SMTP_HOST:-}" }
            - { name: SMTP_PORT, value: "${TD_SMTP_PORT:-587}" }
            - { name: SMTP_USERNAME, value: "${TD_SMTP_USERNAME:-}" }
            - name: SMTP_PASSWORD
              valueFrom: { secretKeyRef: { name: tracedown-secrets, key: SMTP_PASSWORD } }
            - { name: EMAIL_SMTP_HOST, value: "${TD_SMTP_HOST:-}" }
            - { name: EMAIL_SMTP_PORT, value: "${TD_SMTP_PORT:-587}" }
            - { name: EMAIL_SMTP_USERNAME, value: "${TD_SMTP_USERNAME:-}" }
            - name: EMAIL_SMTP_PASSWORD
              valueFrom: { secretKeyRef: { name: tracedown-secrets, key: SMTP_PASSWORD } }
          ports:
            - { containerPort: 20714 }
            - { containerPort: 20870 }
          # The two endpoints answer different questions and must not be
          # crossed over. /ping is deliberately static: it says the process is
          # up, and nothing it touches can fail — so a restart is never
          # triggered by a database or Redis outage that restarting cannot fix.
          # /health actually exercises the pools and returns 503 when a
          # required dependency is down, which is exactly a readiness answer:
          # take the pod out of the Service, leave it running, put it back when
          # the dependency returns.
          livenessProbe:
            httpGet: { path: /ping, port: 20714 }
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet: { path: /health, port: 20714 }
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
          # The jar is fetched by an initContainer and a cold JVM plus Flyway
          # can take a while; the startup probe carries that window so the
          # liveness probe above can stay short afterwards.
          startupProbe:
            httpGet: { path: /ping, port: 20714 }
            periodSeconds: 5
            failureThreshold: 60
          volumeMounts:
            - { name: app, mountPath: /app }
            - { name: bodies, mountPath: /data/bodies }
      volumes:
        - name: app
          emptyDir: {}
        - name: bodies
          persistentVolumeClaim: { claimName: tracedown-bodies }
---
apiVersion: v1
kind: Service
metadata: { name: tracedown, namespace: ${TD_NAMESPACE} }
spec:
  selector: { app: tracedown }
  ports:
    - { name: http, port: 20714 }
    - { name: ws, port: 20870 }
YAML

  if [ -n "$TD_INGRESS_HOST" ]; then
    cat >> tracedown.yaml <<YAML
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tracedown
  namespace: ${TD_NAMESPACE}
  # Add TLS (cert-manager annotation + tls block) before real users.
spec:
  rules:
    - host: ${TD_INGRESS_HOST}
      http:
        paths:
          - path: /ws
            pathType: Prefix
            backend: { service: { name: tracedown, port: { number: 20870 } } }
          - path: /
            pathType: Prefix
            backend: { service: { name: tracedown, port: { number: 20714 } } }
YAML
  fi

  if [ "$TD_EMAIL_MODE" != "smtp" ]; then
    warn "No email provider: mail stays in the pod logs and the production"
    warn "startup guards are NOT armed. Edit the manifest (EMAIL_* / DEPLOYMENT_ENV)"
    warn "and kubectl apply again before real users."
  fi

  if command -v kubectl >/dev/null 2>&1; then
    # The ambient current-context is NEVER used: a workstation's contexts may
    # belong to entirely unrelated clusters, and "apply to whatever happens to
    # be current" is how someone else's production gets a surprise namespace.
    # The target must be typed exactly, must exist, and is passed explicitly.
    note "kubectl contexts on this machine:"
    kubectl config get-contexts -o name 2>/dev/null | sed 's/^/      /' || true
    prompt TD_K8S_CONTEXT "Type the EXACT context to apply to (empty or 'skip': don't apply)" ""
    [ "$TD_K8S_CONTEXT" = "skip" ] && TD_K8S_CONTEXT=""
    if [ -n "$TD_K8S_CONTEXT" ]; then
      kubectl config get-contexts -o name 2>/dev/null | grep -Fxq "$TD_K8S_CONTEXT" \
        || die "Context '$TD_K8S_CONTEXT' does not exist — nothing was applied."
      kubectl --context "$TD_K8S_CONTEXT" apply -f tracedown.yaml
      say "Applied to '${TD_K8S_CONTEXT}'. Watch: kubectl --context ${TD_K8S_CONTEXT} -n ${TD_NAMESPACE} rollout status deploy/tracedown"
    else
      note "Not applied — review $(pwd)/tracedown.yaml and apply when ready."
    fi
  else
    note "kubectl not found — manifests written to $(pwd)/tracedown.yaml; apply from a machine with cluster access."
  fi

  say "Done."
  local dashboard
  if [ -n "$TD_INGRESS_HOST" ]; then
    dashboard="http://${TD_INGRESS_HOST}/"
    note "Dashboard: ${dashboard} once the Ingress resolves (add TLS!)."
  else
    dashboard="http://127.0.0.1:20714"
    note "No Ingress: kubectl -n ${TD_NAMESPACE} port-forward svc/tracedown 20714:20714"
    note "then open ${dashboard}"
  fi
  report_first_login "$dashboard" "$(pwd)/tracedown.yaml"
  note "Docs: ${DOCS}/install/monolith/"
}
