#!/usr/bin/env bash
# Tracedown installer — "monolith" mode. Sourced by install.sh, which provides the
# shared helpers (prompt, say, confirm_dir, prompt_email, ...) and the TD_*
# environment contract. Not runnable on its own.



install_monolith() {
  say "Monolith: the whole platform in one container, plus Postgres and Redis."

  prompt TD_DIR      "Install directory"                        "$HOME/tracedown"
  prompt TD_VERSION  "Backend version (or 'latest')"            "latest"
  prompt TD_GATEWAY_PORT  "Gateway port (dashboard + API)"      "20714"
  prompt TD_REALTIME_PORT "WebSocket port"                      "20870"
  # Invite and password-reset mails are built from this. It has to be the URL a
  # browser can actually reach, not the loopback the container binds — a link
  # to 127.0.0.1 is useless in someone else's inbox.
  prompt TD_APP_URL  "Public base URL (what users' browsers will reach)" "http://127.0.0.1:${TD_GATEWAY_PORT}"
  prompt_admin
  prompt_email

  [ "$TD_VERSION" = "latest" ] && TD_VERSION="$(latest_backend_version)"
  [ -n "$TD_VERSION" ] || die "Could not resolve the latest release."
  confirm_dir "$TD_DIR"; cd "$TD_DIR"

  say "Fetching tracedown-monolith ${TD_VERSION} ..."
  curl -fsSL -o monolith.jar \
    "https://github.com/${BACKEND_REPO}/releases/download/v${TD_VERSION}/tracedown-monolith-${TD_VERSION}-all.jar"

  if [ ! -f .env ]; then
    say "Generating secrets (.env) ..."
    cat > .env <<ENV
# Generated by install.sh — keep this file safe.
# PLATFORM_AES_KEY is permanent: it encrypts stored secrets and cannot be
# rotated; losing it orphans that data. Back it up separately from the database.
PLATFORM_AES_KEY=$(hex32)
JWT_SECRET=$(b64secret)
DB_PASSWORD=$(openssl rand -hex 16)
GATEWAY_PORT=${TD_GATEWAY_PORT}
REALTIME_PORT=${TD_REALTIME_PORT}
APP_URL=${TD_APP_URL}
# First-run bootstrap: creates the organization below and its owner. This is
# the only way to get the first account — invites and --create-org both need a
# user to exist. Set it to false once you have signed in, then 'up -d' again.
SINGLE_ORG_MODE=true
DEMO_USER_EMAIL=${TD_DEMO_EMAIL}
DEMO_USER_PASSWORD=${TD_DEMO_PASSWORD}
ENV
    if [ "$TD_EMAIL_MODE" = "smtp" ]; then
      cat >> .env <<ENV
DEPLOYMENT_ENV=production
EMAIL_PROVIDER=smtp
EMAIL_FROM_ADDRESS=${TD_EMAIL_FROM}
EMAIL_SMTP_HOST=${TD_SMTP_HOST}
EMAIL_SMTP_PORT=${TD_SMTP_PORT}
EMAIL_SMTP_USERNAME=${TD_SMTP_USERNAME}
EMAIL_SMTP_PASSWORD=${TD_SMTP_PASSWORD}
ENV
    else
      cat >> .env <<'ENV'
# No email provider yet: mail stays in the container logs, and the stack runs
# WITHOUT the production startup guards (the platform refuses console mail in
# production). Before real users: configure SMTP here and set
# DEPLOYMENT_ENV=production, then `docker compose up -d`.
EMAIL_PROVIDER=console
ENV
    fi
    chmod 600 .env
  else
    note "Reusing existing .env"
    grep -q '^SINGLE_ORG_MODE=' .env || warn \
      "This .env has no SINGLE_ORG_MODE. If no account exists yet, add SINGLE_ORG_MODE=true (with real DEMO_USER_* values) before starting — nothing else can create the first user."
  fi

  cat > docker-compose.yml <<'YML'
# Tracedown monolith — generated by install.sh. `docker compose up -d` here.
name: tracedown-monolith

services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: tracedown
      POSTGRES_USER: tracedown
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # PostgreSQL 18 images keep the cluster at /var/lib/postgresql/18/docker, so the volume mounts the parent — not the pre-18 /var/lib/postgresql/data.
    volumes: [pgdata:/var/lib/postgresql]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes: [redisdata:/data]
    restart: unless-stopped

  monolith:
    image: eclipse-temurin:17-jre
    command: ["java", "-jar", "/tracedown/monolith.jar"]
    volumes:
      - ./monolith.jar:/tracedown/monolith.jar:ro
      - bodies:/data/bodies
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/tracedown
      DATABASE_USER: tracedown
      DATABASE_PASSWORD: ${DB_PASSWORD}
      REDIS_A_URL: redis://redis:6379
      PLATFORM_AES_KEY: ${PLATFORM_AES_KEY}
      JWT_SECRET: ${JWT_SECRET}
      # Everything below passes through from .env — edit there, `up -d` again.
      DEPLOYMENT_ENV: ${DEPLOYMENT_ENV:-}
      EMAIL_PROVIDER: ${EMAIL_PROVIDER:-console}
      # These two repeat the platform's OWN defaults rather than "". A key
      # present here always reaches the process, and the platform treats a
      # defined-but-empty value as an override — an empty APP_URL turns every
      # invite and password-reset link in outgoing mail into a bare path.
      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS:-noreply@tracedown.dev}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-587}
      EMAIL_SMTP_USERNAME: ${EMAIL_SMTP_USERNAME:-}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD:-}
      WS_URL: ${WS_URL:-}
      APP_URL: ${APP_URL:-http://localhost:5173}
      STORAGE_FILESYSTEM_ROOT: /data/bodies
      # Compose does NOT hand .env to the container — only to the interpolation
      # on the right of these colons. A variable missing from this map never
      # reaches the process, however carefully .env sets it.
      SINGLE_ORG_MODE: ${SINGLE_ORG_MODE:-false}
      DEMO_USER_EMAIL: ${DEMO_USER_EMAIL}
      DEMO_USER_PASSWORD: ${DEMO_USER_PASSWORD}
    ports:
      - "127.0.0.1:${GATEWAY_PORT}:20714"
      - "127.0.0.1:${REALTIME_PORT}:20870"
    depends_on: [postgres, redis]
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  bodies:
YML

  say "Starting (docker compose up -d) ..."
  docker compose up -d
  # /health, not /ping: /ping is static liveness and answers as soon as the
  # event loop is up, which is well before the database is migrated and
  # reachable. /health is the readiness endpoint and 503s until it is.
  wait_for_ping "http://127.0.0.1:${TD_GATEWAY_PORT}/health" 180 || true

  say "Done."
  note "Dashboard:  http://127.0.0.1:${TD_GATEWAY_PORT}"
  report_first_login "http://127.0.0.1:${TD_GATEWAY_PORT}" "${TD_DIR}/.env"
  note "Both ports bind 127.0.0.1 only — put your web server in front for the"
  note "network: proxy / to ${TD_GATEWAY_PORT} and /ws (WebSocket) to ${TD_REALTIME_PORT},"
  note "and set WS_URL=/ws in .env so the dashboard connects same-origin."
  note "Docs: ${DOCS}/install/monolith/"
}

